---
# tasks file for tendrl-node

- name: Make sure that libselinux-python is installed
  yum:
    name: libselinux-python
    state: latest

- name: Switch SELinux targeted policy to expected mode
  selinux:
    policy: targeted
    state: "{{ selinux_mode }}"

- name: Install tendrl-selinux
  yum:
    name=tendrl-selinux
    state=latest

- name: Install tendrl-collectd-selinux
  yum:
    name=tendrl-collectd-selinux
    state=latest

- include: rsyslog.yml
- include: tendrl-node-agent.yml
