---

- name: Install tendrl-notifier
  yum:
    name=tendrl-notifier
    state=latest

- name: Configure etcd fqdn in notifier.conf.yaml
  lineinfile:
    dest: /etc/tendrl/notifier/notifier.conf.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^etcd_connection:.*'
      line: "etcd_connection: {{ etcd_fqdn }}"
  notify:
    - restart tendrl-notifier

- name: Configure etcd client-server authentication
  lineinfile:
    dest: /etc/tendrl/notifier/notifier.conf.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^#? *etcd_ca_cert_file:.*'
      line: "etcd_ca_cert_file: {{ etcd_trusted_ca_file }}"
    - regexp: '^#? *etcd_cert_file:.*'
      line: "etcd_cert_file: {{ etcd_cert_file }}"
    - regexp: '^#? *etcd_key_file:.*'
      line: "etcd_key_file: {{ etcd_key_file }}"
  notify:
    - restart tendrl-notifier
  when: etcd_tls_client_auth|bool == True

#
# email notifications
#

- name: Configure email source (done only when email config is provided)
  lineinfile:
    dest: /etc/tendrl/notifier/email.conf.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^#? *email_id:.*'
      line: "email_id: {{ tendrl_notifier_email_id }}"
    - regexp: '^#? *email_smtp_server:.*'
      line: "email_smtp_server: {{ tendrl_notifier_email_smtp_server }} "
    - regexp: '^#? *email_smtp_port:.*'
      line: "email_smtp_port: {{ tendrl_notifier_email_smtp_port }}"
  when: tendrl_notifier_email_id is defined and tendrl_notifier_email_smtp_server is defined
  notify:
    - restart tendrl-notifier

- name: Configure notifier email auth (optional)
  lineinfile:
    dest: /etc/tendrl/notifier/email.conf.yaml
    regexp: '^#? *auth:.*'
    line: "auth: {{ tendrl_notifier_email_auth }}"
  when: tendrl_notifier_email_auth is defined
  notify:
    - restart tendrl-notifier

- name: Configure notifier email password (optional)
  lineinfile:
    dest: /etc/tendrl/notifier/email.conf.yaml
    regexp: '^#? *email_pass:.*'
    line: "email_pass: {{ tendrl_notifier_email_pass }}"
  when: tendrl_notifier_email_pass is defined
  notify:
    - restart tendrl-notifier

#
# snmp notifications
#

- name: Configure snmp (done only when snmp config is provided)
  copy:
    src: "{{ tendrl_notifier_snmp_conf_file }}"
    dest: /etc/tendrl/notifier/snmp.conf.yaml
    backup: yes
    mode: 0640
  when: tendrl_notifier_snmp_conf_file is defined
  notify:
    - restart tendrl-notifier

- name: Enable tendrl-notifier service
  service:
    name=tendrl-notifier
    enabled=yes

- name: Start tendrl-notifier service
  service:
    name=tendrl-notifier
    state=started
